# Generated by Django 5.0.7 on 2024-07-20 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='makale',
            name='guncellenme_tarihi',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
